### PR TITLE
Update

### PR DESCRIPTION
**Pull request by ghost**
+ Updated the code found in the master repo, also added a bit more custom ability such as where logs are located, and which port to utilize. 
+ Changed the file structure so that it became more organized
+ Added install/uninstall which allows you to install the honeypot to the local system.
+ Some smaller changes to the Dockerfile to reflect the other changes.

### CODE REVIEW

**Comment by t3chn0m4g3** [comment]
@schmalle Have you reviewed this by any chance?

**Comment by schmalle** [comment]
> @schmalle Have you had the time to review this by any chance?

just doing

**Comment by schmalle** [comment]
> * Updated the code found in the master repo, also added a bit more custom ability such as where logs are located, and which port to utilize.
> * Changed the file structure so that it became more organized
> * Added install/uninstall which allows you to install the honeypot to the local system.
> * Some smaller changes to the Dockerfile to reflect the other changes.

Thanks a lot and sorry for far too long reaction time

**Review by schmalle — APPROVED** [review]

**Review by schmalle — APPROVED** [review]
Thanks a lot

**Review by schmalle — APPROVED** [review]
Thanks a lot

**Comment by s9rA16Bf4** [comment]
No problem, just happy to be able to contribute.

**Comment by schmalle** [comment]
> No problem, just happy to be able to contribute.

to be open, i never used pull requests, just figuring out and commit it in the next two hours, stay healthy

**Comment by t3chn0m4g3** [comment]
Awesome @s9rA16Bf4 @schmalle

**Comment by t3chn0m4g3** [comment]
@s9rA16Bf4 Building works just fine, however on connection I am getting the following error and medpot crashes:
```
medpot    | {"level":"info","message":"Connection found","timestamp":"13 Jun 22 10:47 UTC","src_port":"39192","src_ip":"172.21.0.1","data":"Ck1TSHxeflwmfEFEVDF8TUNNfExBQkFEVHxNQ018MTk4ODA4MTgxMTI2fFNFQ1VSSVRZfEFEVF5BMDF8TVNHMDAwMDEtfFB8Mi42CkVWTnxBMDF8MTk4ODA4MTgxMTIzClBJRHx8fFBBVElEMTIzNF41Xk0xMV5eQU58fEpPTkVTXldJTExJQU1eQV5JSUl8fDE5NjEwNjE1fE18fDIxMDYtM3w2NzcgREVMQVdBUkUgQVZFTlVFXl5FVkVSRVRUXk1BXjAyMTQ5fEdMfCg5MTkpMzc5LTEyMTJ8KDkxOSkyNzEtMzQzNH4oOTE5KTI3Ny0zMTE0fHxTfHxQQVRJRDEyMzQ1MDAxXjJeTTEwXl5BQ1NOfDEyMzQ1Njc4OXw5LTg3NjU0Xk5DCk5LMXwxfEpPTkVTXkJBUkJBUkFeS3xTUE98fHx8fDIwMDExMTA1Ck5LMXwxfEpPTkVTXk1JQ0hBRUxeQXxGVEgKUFYxfDF8SXwyMDAwXjIwMTJeMDF8fHx8MDA0Nzc3XkxFQkFVRVJeU0lETkVZXkoufHx8U1VSfHwtfHxBRE18QTAKQUwxfDF8fF5QRU5JQ0lMTElOfHxDT0RFMTZ+Q09ERTE3fkNPREUxOApBTDF8Mnx8XkNBVCBEQU5ERVJ8fENPREUyNTcKREcxfDAwMXxJOXwxNTUwfE1BTCBORU8gTElWRVIsIFBSSU1BUll8MTk4ODA1MDExMDMwMDV8RgpQUjF8MjIzNHxNMTF8MTExXkNPREUxNTF8Q09NTU9OIFBST0NFRFVSRVN8MTk4ODA5MDgxMTIzClJPTHw0NV5SRUNPUkRFUl5ST0xFIE1BU1RFUiBMSVNUfEFEfFJPfEtBVEVeU01JVEheRUxMRU58MTk5NTA1MDExMjAxCkdUMXwxMTIyfDE1MTl8QklMTF5HQVRFU15BCklOMXwwMDF8QTM1N3wxMjM0fEJDTUR8fHx8fDEzMjk4NwpJTjJ8SUQxNTUxMDAxfFNTTjEyMzQ1Njc4ClJPTHw0NV5SRUNPUkRFUl5ST0xFIE1BU1RFUiBMSVNUfEFEfFJPfEtBVEVeRUxMRU58MTk5NTA1MDExMjAxCg=="}
medpot    | [!] Warning: Failed to read file '/etc/medpot/ews.xml'
medpot    | [*] Inform: Http reponse status: 200 OK
medpot    | [*] Inform: Increased counter to 1
medpot    | #### Error ####
medpot    | msg: read tcp 172.21.0.2:2575->172.21.0.1:39192: i/o timeout
medpot    | where: medpot.handleRequest()
medpot exited with code 1
```

It does not seem to be a permission issue, even with `777` and running as `root` the behavior persists. Maybe I am overlooking something...


My Dockerfile:
```
FROM alpine:3.16
#
# Setup apk
RUN apk -U --no-cache add \
                   build-base \
                   git \
                   go \
                   g++ && \
#
# Setup go, build medpot
    export GOPATH=/tmp && \
    export GO111MODULE=off && \
    cd /tmp && \
    go get -d -v github.com/davecgh/go-spew/spew && \
    go get -d -v github.com/go-ini/ini && \
    go get -d -v github.com/mozillazg/request && \
    go get -d -v go.uber.org/zap && \
    go get -d -v github.com/s9rA16Bf4/ArgumentParser/go/arguments && \
    go get -d -v github.com/s9rA16Bf4/notify_handler/go/notify && \
    git clone https://github.com/schmalle/medpot && \
    cd medpot && \
#    git checkout 75a2e6134cf926c35b6017d62542274434c87388 && \
    git checkout 3ec8740258d85ab3558659c727226d752ecaa43f && \
    sed -i s/"ews = true"/"ews = false"/g template/ews.cfg && \
    go build -o medpot go/medpot.go go/logo.go && \
#
# Setup medpot
    mkdir -p /etc/medpot \
             /opt/medpot \
             /var/log/medpot && \
    cp medpot /opt/medpot && \
    cp ./template/* /etc/medpot && \
#
# Setup user, groups and configs
    addgroup -g 2000 medpot && \
    adduser -S -s /bin/ash -u 2000 -D -g 2000 medpot && \
    chown -R medpot:medpot /var/log/medpot && \
#
# Clean up
    apk del --purge build-base \
                    git \
                    go \
                    g++ && \
    rm -rf /var/cache/apk/* \
           /opt/go \
           /root/dist
#
# Start medpot
WORKDIR /opt/medpot
USER medpot:medpot
CMD ["./medpot"]
```

My docker-compose:
```
version: '2.3'

networks:
  medpot_local:

services:

# medpot service
  medpot:
    build: .
    container_name: medpot
    restart: always
#    cpu_count: 1
#    cpus: 0.25
    networks:
     - medpot_local
    ports:
     - "2575:2575"
    image: "dtagdevsec/medpot:2204"
    read_only: true
    volumes:
     - /data/medpot/log/:/var/log/medpot
```

**Comment by ghost** [comment]
Thank you for the report.

Where you doing anything special with the honeypot before this happend?

**Comment by t3chn0m4g3** [comment]
Nope, started it freshly for testing, nothing else.

**Comment by t3chn0m4g3** [comment]
For comparison... this is the output from the version before the merge ...
```
medpot    | {"level":"info","message":"Connection found","timestamp":"2022-06-13T12:42:59Z","src_port":"34428","src_ip":"172.22.0.1","data":"Ck1TSHxeflwmfEFEVDF8TUNNfExBQkFEVHxNQ018MTk4ODA4MTgxMTI2fFNFQ1VSSVRZfEFEVF5BMDF8TVNHMDAwMDEtfFB8Mi42CkVWTnxBMDF8MTk4ODA4MTgxMTIzClBJRHx8fFBBVElEMTIzNF41Xk0xMV5eQU58fEpPTkVTXldJTExJQU1eQV5JSUl8fDE5NjEwNjE1fE18fDIxMDYtM3w2NzcgREVMQVdBUkUgQVZFTlVFXl5FVkVSRVRUXk1BXjAyMTQ5fEdMfCg5MTkpMzc5LTEyMTJ8KDkxOSkyNzEtMzQzNH4oOTE5KTI3Ny0zMTE0fHxTfHxQQVRJRDEyMzQ1MDAxXjJeTTEwXl5BQ1NOfDEyMzQ1Njc4OXw5LTg3NjU0Xk5DCk5LMXwxfEpPTkVTXkJBUkJBUkFeS3xTUE98fHx8fDIwMDExMTA1Ck5LMXwxfEpPTkVTXk1JQ0hBRUxeQXxGVEgKUFYxfDF8SXwyMDAwXjIwMTJeMDF8fHx8MDA0Nzc3XkxFQkFVRVJeU0lETkVZXkoufHx8U1VSfHwtfHxBRE18QTAKQUwxfDF8fF5QRU5JQ0lMTElOfHxDT0RFMTZ+Q09ERTE3fkNPREUxOApBTDF8Mnx8XkNBVCBEQU5ERVJ8fENPREUyNTcKREcxfDAwMXxJOXwxNTUwfE1BTCBORU8gTElWRVIsIFBSSU1BUll8MTk4ODA1MDExMDMwMDV8RgpQUjF8MjIzNHxNMTF8MTExXkNPREUxNTF8Q09NTU9OIFBST0NFRFVSRVN8MTk4ODA5MDgxMTIzClJPTHw0NV5SRUNPUkRFUl5ST0xFIE1BU1RFUiBMSVNUfEFEfFJPfEtBVEVeU01JVEheRUxMRU58MTk5NTA1MDExMjAxCkdUMXwxMTIyfDE1MTl8QklMTF5HQVRFU15BCklOMXwwMDF8QTM1N3wxMjM0fEJDTUR8fHx8fDEzMjk4NwpJTjJ8SUQxNTUxMDAxfFNTTjEyMzQ1Njc4ClJPTHw0NV5SRUNPUkRFUl5ST0xFIE1BU1RFUiBMSVNUfEFEfFJPfEtBVEVeRUxMRU58MTk5NTA1MDExMjAxCg=="}
medpot    | Http Reponse 200 OK
medpot    | Increase counter ...
medpot    | Error reading: read tcp 172.22.0.2:2575->172.22.0.1:34428: i/o timeout
```

**Comment by ghost** [comment]
I'll look into it now, think I got a general idea on what could be wrong.

**Comment by t3chn0m4g3** [comment]
Thank you @s9rA16Bf4 !

**Comment by ghost** [comment]
@t3chn0m4g3 I released a potential patch for the program exiting on timeout, would it be possible for you to check if it fixes the issue?

https://github.com/s9rA16Bf4/medpot

**Comment by t3chn0m4g3** [comment]
Yes, just a Minute.

**Comment by t3chn0m4g3** [comment]
It does not seem to crash any longer, however it still does not seem to be able to read the `ews.xml`:
```
medpot    | {"level":"info","message":"Connection found","timestamp":"13 Jun 22 15:11 UTC","src_port":"52482","src_ip":"172.23.0.1","data":"Ck1TSHxeflwmfEFEVDF8TUNNfExBQkFEVHxNQ018MTk4ODA4MTgxMTI2fFNFQ1VSSVRZfEFEVF5BMDF8TVNHMDAwMDEtfFB8Mi42CkVWTnxBMDF8MTk4ODA4MTgxMTIzClBJRHx8fFBBVElEMTIzNF41Xk0xMV5eQU58fEpPTkVTXldJTExJQU1eQV5JSUl8fDE5NjEwNjE1fE18fDIxMDYtM3w2NzcgREVMQVdBUkUgQVZFTlVFXl5FVkVSRVRUXk1BXjAyMTQ5fEdMfCg5MTkpMzc5LTEyMTJ8KDkxOSkyNzEtMzQzNH4oOTE5KTI3Ny0zMTE0fHxTfHxQQVRJRDEyMzQ1MDAxXjJeTTEwXl5BQ1NOfDEyMzQ1Njc4OXw5LTg3NjU0Xk5DCk5LMXwxfEpPTkVTXkJBUkJBUkFeS3xTUE98fHx8fDIwMDExMTA1Ck5LMXwxfEpPTkVTXk1JQ0hBRUxeQXxGVEgKUFYxfDF8SXwyMDAwXjIwMTJeMDF8fHx8MDA0Nzc3XkxFQkFVRVJeU0lETkVZXkoufHx8U1VSfHwtfHxBRE18QTAKQUwxfDF8fF5QRU5JQ0lMTElOfHxDT0RFMTZ+Q09ERTE3fkNPREUxOApBTDF8Mnx8XkNBVCBEQU5ERVJ8fENPREUyNTcKREcxfDAwMXxJOXwxNTUwfE1BTCBORU8gTElWRVIsIFBSSU1BUll8MTk4ODA1MDExMDMwMDV8RgpQUjF8MjIzNHxNMTF8MTExXkNPREUxNTF8Q09NTU9OIFBST0NFRFVSRVN8MTk4ODA5MDgxMTIzClJPTHw0NV5SRUNPUkRFUl5ST0xFIE1BU1RFUiBMSVNUfEFEfFJPfEtBVEVeU01JVEheRUxMRU58MTk5NTA1MDExMjAxCkdUMXwxMTIyfDE1MTl8QklMTF5HQVRFU15BCklOMXwwMDF8QTM1N3wxMjM0fEJDTUR8fHx8fDEzMjk4NwpJTjJ8SUQxNTUxMDAxfFNTTjEyMzQ1Njc4ClJPTHw0NV5SRUNPUkRFUl5ST0xFIE1BU1RFUiBMSVNUfEFEfFJPfEtBVEVeRUxMRU58MTk5NTA1MDExMjAxCg=="}
medpot    | [!] Warning: Failed to read file '/etc/medpot/ews.xml'
medpot    | [*] Inform: Http reponse status: 200 OK
medpot    | [*] Inform: Increased counter to 1
medpot    | [*] Inform: read tcp 172.23.0.2:2575->172.23.0.1:52482: i/o timeout
medpot    | [!] Warning: Maximum loop counter reached... loop will now end!
```

**Comment by ghost** [comment]
Okay thanks for checking it out! It's good that it's not crashing anymore. 
I'm having some issue compiling the docker file on my end, seems like `go get` is getting some parts deprecated in go 1.18, could you make sure that the `ews.xml` file exists in `/etc/medpot/`?

**Comment by t3chn0m4g3** [comment]
LGTM:
```
docker exec -it medpot ash
/opt/medpot $ ls -al /etc/medpot/
total 24
drwxr-xr-x    2 root     root          4096 Jun 13 15:11 .
drwxr-xr-x    1 root     root          4096 Jun 13 15:11 ..
-rw-r--r--    1 root     root          3341 Jun 13 15:11 dummyerror.xml
-rw-r--r--    1 root     root           157 Jun 13 15:11 dummyok.xml
-rw-r--r--    1 root     root          2407 Jun 13 15:11 ews.cfg
-rw-r--r--    1 root     root           686 Jun 13 15:11 ews.xml
/opt/medpot $
```

**Comment by ghost** [comment]
Found the issue, but now it results in a 500 server error when it tries to post to `https://community.sicherheitstacho.eu/ews-0.1/alert/postSimpleMessage`  and I can't really figure out why as the json being sent is identical. 

The only thing different is the timestamp, as we currently are using `RFC822` instead of `RFC3339` but reverting back to the old one did not help.

**Comment by t3chn0m4g3** [comment]
For the T-Pot use case log submission is ensured through ewsposter and thus I turn off EWS submission for the medpot image. Does not help for the standalone use case though as @schmalle intended.

**Comment by ghost** [comment]
So you could create a flag, i.e. `--standalone` which would in turn disable the `post()` function?

**Comment by t3chn0m4g3** [comment]
It would probably be enough to parse ews.cfg on start. If `ews = false` then disable the post.

**Comment by ghost** [comment]
Fixed it in my latest commit, if it all works as intended now then I will do a pull request :)

**Comment by t3chn0m4g3** [comment]
Perfect, thank you ...

```
medpot    | {"level":"info","message":"Connection found","timestamp":"13 Jun 22 16:48 UTC","src_port":"57506","src_ip":"172.24.0.1","data":"Ck1TSHxeflwmfEFEVDF8TUNNfExBQkFEVHxNQ018MTk4ODA4MTgxMTI2fFNFQ1VSSVRZfEFEVF5BMDF8TVNHMDAwMDEtfFB8Mi42CkVWTnxBMDF8MTk4ODA4MTgxMTIzClBJRHx8fFBBVElEMTIzNF41Xk0xMV5eQU58fEpPTkVTXldJTExJQU1eQV5JSUl8fDE5NjEwNjE1fE18fDIxMDYtM3w2NzcgREVMQVdBUkUgQVZFTlVFXl5FVkVSRVRUXk1BXjAyMTQ5fEdMfCg5MTkpMzc5LTEyMTJ8KDkxOSkyNzEtMzQzNH4oOTE5KTI3Ny0zMTE0fHxTfHxQQVRJRDEyMzQ1MDAxXjJeTTEwXl5BQ1NOfDEyMzQ1Njc4OXw5LTg3NjU0Xk5DCk5LMXwxfEpPTkVTXkJBUkJBUkFeS3xTUE98fHx8fDIwMDExMTA1Ck5LMXwxfEpPTkVTXk1JQ0hBRUxeQXxGVEgKUFYxfDF8SXwyMDAwXjIwMTJeMDF8fHx8MDA0Nzc3XkxFQkFVRVJeU0lETkVZXkoufHx8U1VSfHwtfHxBRE18QTAKQUwxfDF8fF5QRU5JQ0lMTElOfHxDT0RFMTZ+Q09ERTE3fkNPREUxOApBTDF8Mnx8XkNBVCBEQU5ERVJ8fENPREUyNTcKREcxfDAwMXxJOXwxNTUwfE1BTCBORU8gTElWRVIsIFBSSU1BUll8MTk4ODA1MDExMDMwMDV8RgpQUjF8MjIzNHxNMTF8MTExXkNPREUxNTF8Q09NTU9OIFBST0NFRFVSRVN8MTk4ODA5MDgxMTIzClJPTHw0NV5SRUNPUkRFUl5ST0xFIE1BU1RFUiBMSVNUfEFEfFJPfEtBVEVeU01JVEheRUxMRU58MTk5NTA1MDExMjAxCkdUMXwxMTIyfDE1MTl8QklMTF5HQVRFU15BCklOMXwwMDF8QTM1N3wxMjM0fEJDTUR8fHx8fDEzMjk4NwpJTjJ8SUQxNTUxMDAxfFNTTjEyMzQ1Njc4ClJPTHw0NV5SRUNPUkRFUl5ST0xFIE1BU1RFUiBMSVNUfEFEfFJPfEtBVEVeRUxMRU58MTk5NTA1MDExMjAxCg=="}
medpot    | [*] Inform: Increased counter to 1
medpot    | [*] Inform: read tcp 172.24.0.2:2575->172.24.0.1:57506: i/o timeout
medpot    | [!] Warning: Maximum loop counter reached... loop will now end!
```

**Pull request merged**
